import { ref, computed } from "vue";
import { defineStore } from "pinia";

export const useProductStore = defineStore("product", () => {
  const products = ref([
    // ------- 皮鞋系列 leather-shoes -------
    {
      id: 1,
      category: "leather-shoes",
      name: "紳士格調經典牛津皮鞋",
      price: 6980,
      originalPrice: 7980,
      style: "oxford",
      color: "black",
      material: "頭層牛皮",
      rating: 5,
      reviews: 156,
      stock: 9,
      image: "/images/product-1.jpg",
      isNew: false,
      discount: 13,
    },
    {
      id: 2,
      category: "leather-shoes",
      name: "摩登時尚簡約牛津皮鞋",
      price: 4980,
      originalPrice: null,
      style: "oxford",
      color: "brown",
      material: "頭層牛皮",
      rating: 4,
      reviews: 134,
      stock: 16,
      image: "/images/product-2.jpg",
      isNew: true,
      discount: 0,
    },
    {
      id: 3,
      category: "leather-shoes",
      name: "復古風範雕花牛津皮鞋",
      price: 7980,
      originalPrice: 8980,
      style: "oxford",
      color: "burgundy",
      material: "頭層牛皮 + 手工雕花",
      rating: 5,
      reviews: 98,
      stock: 4,
      image: "/images/product-3.jpg",
      isNew: true,
      discount: 11,
    },
    {
      id: 4,
      category: "leather-shoes",
      name: "商務精英德比皮鞋",
      price: 5980,
      originalPrice: null,
      style: "derby",
      color: "black",
      material: "頭層牛皮",
      rating: 4,
      reviews: 87,
      stock: 0,
      image: "/images/product-4.jpg",
      isNew: false,
      discount: 0,
    },
    {
      id: 5,
      category: "leather-shoes",
      name: "都會型男樂福鞋",
      price: 5400,
      originalPrice: null,
      style: "loafer",
      color: "brown",
      material: "小牛皮",
      rating: 5,
      reviews: 76,
      stock: 10,
      image: "/images/product-5.jpg",
      isNew: true,
      discount: 0,
    },
    {
      id: 6,
      category: "leather-shoes",
      name: "義式經典樂福鞋",
      price: 8800,
      originalPrice: 9800,
      style: "loafer",
      color: "tan",
      material: "義大利進口小牛皮",
      rating: 5,
      reviews: 112,
      stock: 6,
      image: "/images/product-6.jpg",
      isNew: false,
      discount: 10,
    },
    {
      id: 7,
      category: "leather-shoes",
      name: "雙扣孟克鞋",
      price: 7680,
      originalPrice: null,
      style: "monk",
      color: "brown",
      material: "頭層牛皮",
      rating: 4,
      reviews: 64,
      stock: 13,
      image: "/images/product-7.jpg",
      isNew: true,
      discount: 0,
    },
    {
      id: 8,
      category: "leather-shoes",
      name: "紳士雕花德比鞋",
      price: 6780,
      originalPrice: 7580,
      style: "derby",
      color: "burgundy",
      material: "頭層牛皮 + 雕花",
      rating: 5,
      reviews: 89,
      stock: 2,
      image: "/images/product-8.jpg",
      isNew: false,
      discount: 11,
    },
    {
      id: 9,
      category: "leather-shoes",
      name: "時尚尖頭牛津鞋",
      price: 5880,
      originalPrice: null,
      style: "oxford",
      color: "black",
      material: "漆皮",
      rating: 4,
      reviews: 45,
      stock: 8,
      image: "/images/product-9.jpg",
      isNew: true,
      discount: 0,
    },

    // ------- 靴子系列 boots -------
    {
      id: 101,
      category: "boots",
      name: "經典切爾西靴",
      price: 8980,
      originalPrice: null,
      style: "chelsea",
      color: "black",
      material: "頭層牛皮",
      features: ["彈性側邊", "防滑鞋底"],
      waterproof: false,
      rating: 5,
      reviews: 145,
      stock: 12,
      image: "/images/product-10.jpg",
      isNew: true,
      discount: 0,
    },
    {
      id: 102,
      category: "boots",
      name: "工裝馬丁靴",
      price: 7680,
      originalPrice: 8980,
      style: "martin",
      color: "black",
      material: "油蠟皮",
      features: ["防水", "耐磨", "8孔設計"],
      waterproof: true,
      rating: 5,
      reviews: 234,
      stock: 8,
      image: "/images/product-11.jpg",
      isNew: false,
      discount: 14,
    },
    {
      id: 103,
      category: "boots",
      name: "經典沙漠靴",
      price: 6280,
      originalPrice: null,
      style: "chukka",
      color: "tan",
      material: "磨砂皮",
      features: ["透氣", "輕量"],
      waterproof: false,
      rating: 4,
      reviews: 98,
      stock: 3,
      image: "/images/product-12.jpg",
      isNew: true,
      discount: 0,
    },
    {
      id: 104,
      category: "boots",
      name: "復古工裝靴",
      price: 9280,
      originalPrice: 10280,
      style: "work",
      color: "brown",
      material: "油蠟皮",
      features: ["防水", "鋼頭", "防滑"],
      waterproof: true,
      rating: 5,
      reviews: 167,
      stock: 6,
      image: "/images/product-13.jpg",
      isNew: false,
      discount: 10,
    },
    {
      id: 105,
      category: "boots",
      name: "紳士切爾西靴",
      price: 10800,
      originalPrice: null,
      style: "chelsea",
      color: "brown",
      material: "義大利進口小牛皮",
      features: ["固特異工藝", "真皮內裡"],
      waterproof: false,
      rating: 5,
      reviews: 89,
      stock: 0,
      image: "/images/product-14.jpg",
      isNew: true,
      discount: 0,
    },
    {
      id: 106,
      category: "boots",
      name: "街頭馬丁靴",
      price: 6980,
      originalPrice: 7980,
      style: "martin",
      color: "black",
      material: "光面皮",
      features: ["經典8孔", "防滑鞋底"],
      waterproof: false,
      rating: 4,
      reviews: 203,
      stock: 15,
      image: "/images/product-15.jpg",
      isNew: false,
      discount: 13,
    },
    {
      id: 107,
      category: "boots",
      name: "都會沙漠靴",
      price: 7480,
      originalPrice: null,
      style: "chukka",
      color: "gray",
      material: "磨砂皮",
      features: ["輕量", "透氣"],
      waterproof: false,
      rating: 4,
      reviews: 76,
      stock: 9,
      image: "/images/product-16.jpg",
      isNew: true,
      discount: 0,
    },
    {
      id: 108,
      category: "boots",
      name: "防水工裝靴",
      price: 8680,
      originalPrice: 9480,
      style: "work",
      color: "tan",
      material: "防水皮革",
      features: ["全防水", "耐磨鞋底", "加厚鞋墊"],
      waterproof: true,
      rating: 5,
      reviews: 134,
      stock: 4,
      image: "/images/product-17.jpg",
      isNew: false,
      discount: 8,
    },
    {
      id: 109,
      category: "boots",
      name: "重裝防水工裝靴",
      price: 9480,
      originalPrice: 10280,
      style: "work",
      color: "black",
      material: "防水皮革",
      features: ["全防水", "鋼頭", "耐磨鞋底"],
      waterproof: true,
      rating: 5,
      reviews: 61,
      stock: 10,
      image: "/images/product-18.jpg",
      isNew: true,
      discount: 8,
    },

    // ------- 休閒鞋系列 casual-shoes -------
    {
      id: 201,
      category: "casual-shoes",
      name: "時尚休閒運動鞋",
      price: 3980,
      originalPrice: 4980,
      style: "sneaker",
      color: "white",
      material: "網布 + 真皮",
      features: ["透氣", "輕量", "氣墊"],
      rating: 5,
      reviews: 312,
      stock: 20,
      image: "/images/casual-1.jpg",
      isNew: true,
      isHot: true,
      discount: 20,
    },
    {
      id: 202,
      category: "casual-shoes",
      name: "經典帆布休閒鞋",
      price: 2280,
      originalPrice: null,
      style: "canvas",
      color: "white",
      material: "帆布",
      features: ["透氣", "經典款"],
      rating: 4,
      reviews: 234,
      stock: 2,
      image: "/images/casual-2.jpg",
      isNew: false,
      isHot: true,
      discount: 0,
    },
    {
      id: 203,
      category: "casual-shoes",
      name: "懶人一腳蹬休閒鞋",
      price: 3480,
      originalPrice: null,
      style: "slip-on",
      color: "black",
      material: "小牛皮",
      features: ["輕鬆穿脫", "柔軟"],
      rating: 5,
      reviews: 189,
      stock: 11,
      image: "/images/casual-3.jpg",
      isNew: true,
      isHot: false,
      discount: 0,
    },
    {
      id: 204,
      category: "casual-shoes",
      name: "經典帆船鞋",
      price: 4280,
      originalPrice: 4980,
      style: "boat",
      color: "brown",
      material: "真皮",
      features: ["防滑", "經典款"],
      rating: 4,
      reviews: 156,
      stock: 0,
      image: "/images/casual-4.jpg",
      isNew: false,
      isHot: false,
      discount: 14,
    },
    {
      id: 205,
      category: "casual-shoes",
      name: "輕量運動休閒鞋",
      price: 3680,
      originalPrice: null,
      style: "sneaker",
      color: "gray",
      material: "飛織網布",
      features: ["超輕量", "透氣", "彈力"],
      rating: 5,
      reviews: 267,
      stock: 18,
      image: "/images/casual-5.jpg",
      isNew: true,
      isHot: true,
      discount: 0,
    },
    {
      id: 206,
      category: "casual-shoes",
      name: "復古帆布鞋",
      price: 2680,
      originalPrice: 2980,
      style: "canvas",
      color: "blue",
      material: "帆布",
      features: ["復古風", "百搭"],
      rating: 4,
      reviews: 198,
      stock: 7,
      image: "/images/casual-6.jpg",
      isNew: false,
      isHot: false,
      discount: 10,
    },
    {
      id: 207,
      category: "casual-shoes",
      name: "商務懶人鞋",
      price: 4580,
      originalPrice: null,
      style: "slip-on",
      color: "black",
      material: "頭層牛皮",
      features: ["商務", "舒適"],
      rating: 5,
      reviews: 143,
      stock: 5,
      image: "/images/casual-7.jpg",
      isNew: true,
      isHot: false,
      discount: 0,
    },
    {
      id: 208,
      category: "casual-shoes",
      name: "麂皮帆船鞋",
      price: 4880,
      originalPrice: 5480,
      style: "boat",
      color: "brown",
      material: "麂皮",
      features: ["防滑", "質感"],
      rating: 4,
      reviews: 112,
      stock: 3,
      image: "/images/casual-8.jpg",
      isNew: false,
      isHot: false,
      discount: 11,
    },
    {
      id: 209,
      category: "casual-shoes",
      name: "透氣網面運動鞋",
      price: 2980,
      originalPrice: null,
      style: "sneaker",
      color: "white",
      material: "網布",
      features: ["透氣", "輕量", "運動"],
      rating: 4,
      reviews: 289,
      stock: 14,
      image: "/images/casual-9.jpg",
      isNew: true,
      isHot: true,
      discount: 0,
    },

    // ------- 襪子 socks -------
    {
      id: 301,
      category: "socks",
      name: "精梳棉紳士襪（三入組）",
      price: 680,
      originalPrice: null,
      style: "cotton",
      color: "black",
      material: "精梳棉",
      rating: 5,
      reviews: 88,
      stock: 30,
      image: "/images/sock-1.jpg",
      isNew: true,
      discount: 0,
    },
    {
      id: 302,
      category: "socks",
      name: "竹纖維抗菌襪",
      price: 380,
      originalPrice: 480,
      style: "bamboo",
      color: "gray",
      material: "竹纖維",
      rating: 4,
      reviews: 56,
      stock: 25,
      image: "/images/sock-2.jpg",
      isNew: false,
      discount: 21,
    },
    {
      id: 303,
      category: "socks",
      name: "羊毛保暖襪",
      price: 520,
      originalPrice: null,
      style: "wool",
      color: "brown",
      material: "美麗諾羊毛",
      rating: 5,
      reviews: 41,
      stock: 4,
      image: "/images/sock-3.jpg",
      isNew: true,
      discount: 0,
    },
    {
      id: 304,
      category: "socks",
      name: "商務條紋棉襪",
      price: 420,
      originalPrice: null,
      style: "cotton",
      color: "navy",
      material: "精梳棉",
      rating: 4,
      reviews: 33,
      stock: 18,
      image: "/images/sock-4.jpg",
      isNew: false,
      discount: 0,
    },
    {
      id: 305,
      category: "socks",
      name: "竹纖維透氣船型襪",
      price: 350,
      originalPrice: 420,
      style: "bamboo",
      color: "white",
      material: "竹纖維",
      rating: 4,
      reviews: 27,
      stock: 0,
      image: "/images/sock-5.jpg",
      isNew: false,
      discount: 17,
    },
    {
      id: 306,
      category: "socks",
      name: "羊毛混紡休閒襪",
      price: 480,
      originalPrice: null,
      style: "wool",
      color: "black",
      material: "羊毛混紡",
      rating: 5,
      reviews: 19,
      stock: 12,
      image: "/images/sock-6.jpg",
      isNew: true,
      discount: 0,
    },

    // ------- 皮帶 belts -------
    {
      id: 401,
      category: "belts",
      name: "經典真皮自動扣皮帶",
      price: 2280,
      originalPrice: 2680,
      style: "auto-buckle",
      color: "black",
      material: "頭層牛皮",
      rating: 5,
      reviews: 102,
      stock: 14,
      image: "/images/belt-1.jpg",
      isNew: false,
      discount: 15,
    },
    {
      id: 402,
      category: "belts",
      name: "雙面可用紳士皮帶",
      price: 1980,
      originalPrice: null,
      style: "reversible",
      color: "brown",
      material: "頭層牛皮",
      rating: 4,
      reviews: 67,
      stock: 9,
      image: "/images/belt-2.jpg",
      isNew: true,
      discount: 0,
    },
    {
      id: 403,
      category: "belts",
      name: "義大利真皮針扣皮帶",
      price: 3280,
      originalPrice: null,
      style: "pin-buckle",
      color: "black",
      material: "義大利進口牛皮",
      rating: 5,
      reviews: 45,
      stock: 3,
      image: "/images/belt-3.jpg",
      isNew: true,
      discount: 0,
    },
    {
      id: 404,
      category: "belts",
      name: "商務雙面皮帶",
      price: 2080,
      originalPrice: 2480,
      style: "reversible",
      color: "tan",
      material: "頭層牛皮",
      rating: 4,
      reviews: 38,
      stock: 0,
      image: "/images/belt-4.jpg",
      isNew: false,
      discount: 16,
    },
    {
      id: 405,
      category: "belts",
      name: "自動扣休閒皮帶",
      price: 1680,
      originalPrice: null,
      style: "auto-buckle",
      color: "brown",
      material: "牛皮",
      rating: 4,
      reviews: 29,
      stock: 20,
      image: "/images/belt-5.jpg",
      isNew: false,
      discount: 0,
    },
    {
      id: 406,
      category: "belts",
      name: "手工雕花針扣皮帶",
      price: 2880,
      originalPrice: 3280,
      style: "pin-buckle",
      color: "burgundy",
      material: "頭層牛皮 + 手工雕花",
      rating: 5,
      reviews: 22,
      stock: 6,
      image: "/images/belt-6.jpg",
      isNew: true,
      discount: 12,
    },

    // ------- 包款 bags -------
    {
      id: 501,
      category: "bags",
      name: "頭層牛皮商務公事包",
      price: 6800,
      originalPrice: 7800,
      style: "business",
      color: "black",
      material: "頭層牛皮",
      features: ["筆電夾層", "多隔層設計"],
      rating: 5,
      reviews: 74,
      stock: 5,
      image: "/images/bag-1.jpg",
      isNew: true,
      discount: 13,
    },
    {
      id: 502,
      category: "bags",
      name: "帆布托特包",
      price: 1880,
      originalPrice: null,
      style: "canvas",
      color: "tan",
      material: "帆布 + 皮革提把",
      features: ["耐磨", "輕量"],
      rating: 4,
      reviews: 58,
      stock: 16,
      image: "/images/bag-2.jpg",
      isNew: false,
      discount: 0,
    },
    {
      id: 503,
      category: "bags",
      name: "真皮旅行包",
      price: 8800,
      originalPrice: 9800,
      style: "travel",
      color: "brown",
      material: "頭層牛皮",
      features: ["大容量", "可放置隨身行李"],
      rating: 5,
      reviews: 31,
      stock: 2,
      image: "/images/bag-3.jpg",
      isNew: true,
      discount: 10,
    },
    {
      id: 504,
      category: "bags",
      name: "商務後背包",
      price: 4280,
      originalPrice: null,
      style: "business",
      color: "black",
      material: "防潑水尼龍 + 皮革",
      features: ["USB 充電孔", "防盜拉鍊"],
      rating: 4,
      reviews: 47,
      stock: 8,
      image: "/images/bag-4.jpg",
      isNew: true,
      discount: 0,
    },
    {
      id: 505,
      category: "bags",
      name: "帆布側背包",
      price: 1580,
      originalPrice: 1880,
      style: "canvas",
      color: "gray",
      material: "帆布",
      features: ["輕便", "百搭"],
      rating: 4,
      reviews: 26,
      stock: 0,
      image: "/images/bag-5.jpg",
      isNew: false,
      discount: 16,
    },
    {
      id: 506,
      category: "bags",
      name: "真皮旅行盥洗包",
      price: 1280,
      originalPrice: null,
      style: "travel",
      color: "brown",
      material: "小牛皮",
      features: ["防水內裡", "小巧便攜"],
      rating: 5,
      reviews: 14,
      stock: 11,
      image: "/images/bag-6.jpg",
      isNew: true,
      discount: 0,
    },
  ]);

  const categoryLabels = {
    "leather-shoes": "皮鞋系列",
    boots: "靴子系列",
    "casual-shoes": "休閒鞋系列",
    socks: "襪子",
    belts: "皮帶",
    bags: "包款系列",
  };

  // 依 id 取得單一商品
  const getProductById = (id) => {
    const numericId = Number(id);
    return products.value.find((p) => p.id === numericId) || null;
  };

  // 依分類取得商品清單
  const getProductsByCategory = (category) => {
    return products.value.filter((p) => p.category === category);
  };

  // 相關商品推薦：同分類、排除自己，取前 4 筆
  const getRelatedProducts = (product, limit = 4) => {
    if (!product) return [];
    return products.value
      .filter((p) => p.category === product.category && p.id !== product.id)
      .slice(0, limit);
  };

  const totalCount = computed(() => products.value.length);

  // 商品資料原本沒有「上架/下架」欄位，統一用這個工具判斷狀態，
  // 沒有明確設定 status 的商品一律視為「上架中」，避免要逐一回頭修改所有 mock 資料
  const getStatus = (product) => product.status || "active";

  // 新增商品：id 統一從目前最大 id + 1 開始，避免跟既有商品（含配件類 300~500 區間）衝突
  const createProduct = (data) => {
    const newProduct = {
      id: Math.max(0, ...products.value.map((p) => p.id)) + 1,
      status: "active",
      rating: 0,
      reviews: 0,
      isNew: true,
      discount: 0,
      ...data,
    };
    products.value.push(newProduct);
    return newProduct;
  };

  const updateProduct = (id, updates) => {
    const target = products.value.find((p) => p.id === id);
    if (!target) return;
    Object.assign(target, updates);
  };

  const deleteProduct = (id) => {
    products.value = products.value.filter((p) => p.id !== id);
  };

  const deleteProducts = (ids) => {
    products.value = products.value.filter((p) => !ids.includes(p.id));
  };

  const setProductStatus = (id, status) => {
    const target = products.value.find((p) => p.id === id);
    if (!target) return;
    target.status = status;
  };

  const setProductsStatus = (ids, status) => {
    products.value.forEach((p) => {
      if (ids.includes(p.id)) p.status = status;
    });
  };

  return {
    products,
    categoryLabels,
    totalCount,
    getProductById,
    getProductsByCategory,
    getRelatedProducts,
    getStatus,
    createProduct,
    updateProduct,
    deleteProduct,
    deleteProducts,
    setProductStatus,
    setProductsStatus,
  };
});
